/**
 * machines/fold.js — FoldMachine (West-coast wavefolder) tests
 *
 * A clean sine/triangle core whose harmonics are GENERATED by a wavefolder (+ a
 * timbre FM path). param_spec.js guards the descriptor contract + generic
 * round-trip; this covers audible behaviour. Filter forced wide-open digital to
 * measure the MACHINE spectrum.
 */

import { suite, test, assert, makeOfflineTrack, renderSteps, rms, bandpassRms } from '../../runner.js';

const STEP_SEC = 0.4;
const STEP_LEN = 3;
const DURATION = 0.05 + 2 * STEP_SEC + 0.6;

async function renderFold(overrides) {
  const { track, ctx, sampleRate } = await makeOfflineTrack('fold', DURATION);
  track.setAnalogue(false);
  track.filter.setParam('filter.cutoff', 20000);
  track.filter.setParam('base.lpf', 20000);
  for (const [p, v] of Object.entries(overrides)) track.machine.setParam(p, v);
  const [w] = await renderSteps(track, ctx, sampleRate, 1, STEP_SEC,
    () => ({ note: 48, velocity: 110, length: STEP_LEN }));
  return { w, sampleRate };
}

suite('FoldMachine', () => {

  test('produces audible output', async () => {
    const { w } = await renderFold({});
    assert.gt(rms(w), 0.001, `baseline RMS too low (rms=${rms(w).toFixed(6)})`);
  });

  test('folding brightens the spectrum', async () => {
    // Carrier ≈130.8 Hz at note 48. fold=0 (≈half a fold lobe) is near-monotonic
    // shaping → few harmonics; fold=1 (≈4.5 lobes) folds the wave repeatedly →
    // many harmonics. Measure bandpassRms at the ~650 Hz harmonic region (amplitude
    // -based — spectralCentroid is dominated by the broadband noise FLOOR for these
    // near-tonal signals and is unreliable here).
    const low  = await renderFold({ 'wave': 'sine', 'fold': 0, 'timbre': 0, 'symmetry': 0 });
    const high = await renderFold({ 'wave': 'sine', 'fold': 1, 'timbre': 0, 'symmetry': 0 });
    const bLow  = bandpassRms(low.w, low.sampleRate, 650, 0.5);
    const bHigh = bandpassRms(high.w, high.sampleRate, 650, 0.5);
    assert.gt(bHigh, bLow * 1.5,
      `fold=1 should add upper harmonics (~650 Hz) vs fold=0 (${bHigh.toFixed(6)} vs ${bLow.toFixed(6)})`);
  });

  test('timbre (FM) adds high-spectrum content', async () => {
    // With folding off, the timbre FM path is the only harmonic source. Raising it
    // adds sidebands well above the ~130 Hz carrier.
    const dry = await renderFold({ 'wave': 'sine', 'fold': 0, 'symmetry': 0, 'timbre': 0, 'ratio': 2 });
    const wet = await renderFold({ 'wave': 'sine', 'fold': 0, 'symmetry': 0, 'timbre': 1, 'ratio': 2 });
    const bDry = bandpassRms(dry.w, dry.sampleRate, 800, 1);
    const bWet = bandpassRms(wet.w, wet.sampleRate, 800, 1);
    assert.gt(bWet, bDry * 1.5,
      `timbre=1 should add high content over timbre=0 (${bWet.toFixed(6)} vs ${bDry.toFixed(6)})`);
  });

  test('toJSON/fromJSON round-trips params', async () => {
    const { track } = await makeOfflineTrack('fold', DURATION);
    const m = track.machine;
    m.setParam('wave', 'triangle');
    m.setParam('fold', 0.7);
    m.setParam('symmetry', -0.5);
    m.setParam('timbre', 0.4);
    m.setParam('ratio', 3.5);
    const json = m.toJSON();

    const { track: t2 } = await makeOfflineTrack('fold', DURATION);
    t2.machine.fromJSON(json);
    assert.ok(t2.machine.getParam('wave') === 'triangle', 'wave round-trip');
    assert.near(t2.machine.getParam('fold'), 0.7, 1e-9, 'fold round-trip');
    assert.near(t2.machine.getParam('symmetry'), -0.5, 1e-9, 'symmetry round-trip');
    assert.near(t2.machine.getParam('timbre'), 0.4, 1e-9, 'timbre round-trip');
    assert.near(t2.machine.getParam('ratio'), 3.5, 1e-9, 'ratio round-trip');
  });

});
